In [7]:
#Carregando os dados para as matrizes de Treinamento e de Teste
import csv
XTreino, XTeste, yTreino, yTeste = [], [], [], []
with open('mnist_train.csv', 'r') as entrada:
  ler = csv.reader(entrada)
  next(ler)
  for linha in ler:
    Y = []
    for j in linha:
      Y.append(int(j))
    XTreino.append(Y)
for i in XTreino: 
  yTreino.append(i.pop(0))

with open('mnist_test.csv', 'r') as entrada:
  ler = csv.reader(entrada)
  next(ler)
  for linha in ler:
    Y = []
    for j in linha:
      Y.append(int(j))
    XTeste.append(Y)
for i in XTeste: 
  yTeste.append(i.pop(0))

#for i in range(0,10):
#  print(i, yTeste[i], XTeste[i])


In [8]:
import numpy as np

with open('mnist_test.csv') as file_name:
    array = np.loadtxt(file_name, delimiter=",")

print(array)

[[7. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [4. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 [6. 0. 0. ... 0. 0. 0.]]


In [9]:
array.shape

(10000, 785)